### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by jgm-ktg** [prathik-kaliyambath/casbin-python-client#1]
Hello, for folks new to the project, could you provide more tips on usage such as found at

https://github.com/php-casbin/casbin-client

Specifically the equivalent of the "EnforceRequest" section?

It would be greatly appreciated!

**Comment by pk82869** [comment]
Sure!

**Comment by pk82869** [comment]
Basically all operations supported on the grpc stub are available, but yes I will add a couple of examples as part of the docs.
